from selenium.webdriver.common.by import By
from src.testproject.classes import DriverStepSettings, StepSettings
from src.testproject.decorator import report_assertion_errors
from src.testproject.enums import SleepTimingType
from src.testproject.sdk.drivers import webdriver
import pytest


"""
This pytest test was automatically generated by TestProject
    Project: My first Project
    Package: TestProject.Generated.Tests.MyFirstProject
    Test: Altus
    Generated by: Tom White (twhite.developer@gmail.com)
    Generated on 10/31/2022, 21:27:02
"""


@pytest.fixture()
def driver():
    driver = webdriver.Chrome(token="j3Qoc2WbuvOb4-a4gbXBQ5e7WHbghxqIlzoehw8V3ds",
                              project_name="My first Project",
                              job_name="Altus")
    step_settings = StepSettings(timeout=15000,
                                 sleep_time=500,
                                 sleep_timing_type=SleepTimingType.Before)
    with DriverStepSettings(driver, step_settings):
        yield driver
    driver.quit()


@report_assertion_errors
def test_main(driver):
    """School Analytics for Altus."""
    # Test Parameters
    # Auto generated application URL parameter
    ApplicationURL = "https://school-analytics-r6xsbla5u-tom1209.vercel.app/"

    # 1. Navigate to '{ApplicationURL}'
    # Navigates the specified URL (Auto-generated)
    driver.get(f'{ApplicationURL}')

    # 2. Click 'Search'
    search = driver.find_element(By.XPATH,
                                 "//a[. = 'Search']")
    search.click()

    # 3. Click 'search1'
    search1 = driver.find_element(By.CSS_SELECTOR,
                                  "#search")
    search1.click()

    # 4. Type 'Mohawk College' in 'search1'
    search1 = driver.find_element(By.CSS_SELECTOR,
                                  "#search")
    search1.send_keys("Mohawk College")

    # 5. Click 'Search2'
    search2 = driver.find_element(By.CSS_SELECTOR,
                                  "#searchButton")
    search2.click()

    # 6. Click 'Download School Grades'
    download_school_grades = driver.find_element(By.CSS_SELECTOR,
                                                 "#downloadPDF")
    download_school_grades.click()

    # 7. Click 'DIV'
    div = driver.find_element(By.XPATH,
                              "//div[3]/div/div[1]")
    div.click()

    # 8. Click 'Marky Mark'
    marky_mark = driver.find_element(By.XPATH,
                                     "//div[. = ' Marky Mark']")
    marky_mark.click()

    # 9. Click 'Mohawk College'
    mohawk_college = driver.find_element(By.XPATH,
                                         "//h1[. = 'Mohawk College']")
    mohawk_college.click()

    # 10. Click 'Add Students'
    add_students = driver.find_element(By.XPATH,
                                       "//a[. = 'Add Students']")
    add_students.click()

    # 11. Click 'schoolName'
    schoolname = driver.find_element(By.CSS_SELECTOR,
                                     "#schoolName")
    schoolname.click()

    # 12. Type 'Hogwarts' in 'schoolName'
    schoolname = driver.find_element(By.CSS_SELECTOR,
                                     "#schoolName")
    schoolname.send_keys("Hogwarts")

    # 13. Type 'George Weasley' in 'studentName'
    studentname = driver.find_element(By.CSS_SELECTOR,
                                      "#studentName")
    studentname.send_keys("George Weasley")

    # 14. Type 'Charms' in 'newClass'
    newclass = driver.find_element(By.CSS_SELECTOR,
                                   "#newClass")
    newclass.send_keys("Charms")

    # 15. Scroll window by ('0','50')
    driver.execute_script("window.scrollBy(0,50)")

    # 16. Type '77' in 'newMark'
    newmark = driver.find_element(By.CSS_SELECTOR,
                                  "#newMark")
    newmark.send_keys("77")

    # 17. Click 'Add More Grades'
    add_more_grades = driver.find_element(By.CSS_SELECTOR,
                                          "#addNewGradeButton")
    add_more_grades.click()

    # 18. Scroll window by ('0','52')
    driver.execute_script("window.scrollBy(0,52)")

    # 19. Scroll window by ('0','57')
    driver.execute_script("window.scrollBy(0,57)")

    # 20. Scroll window by ('0','47')
    driver.execute_script("window.scrollBy(0,47)")

    # 21. Scroll window by ('0','13')
    driver.execute_script("window.scrollBy(0,13)")

    # 22. Scroll window by ('0','11')
    driver.execute_script("window.scrollBy(0,11)")

    # 23. Click 'Charms'
    charms = driver.find_element(By.XPATH,
                                 "//td[. = 'Charms']")
    charms.click()

    # 24. Click 'newClass'
    newclass = driver.find_element(By.CSS_SELECTOR,
                                   "#newClass")
    newclass.click()

    # 25. Type 'Potions' in 'newClass'
    newclass = driver.find_element(By.CSS_SELECTOR,
                                   "#newClass")
    newclass.send_keys("Potions")

    # 26. Type '44' in 'newMark'
    newmark = driver.find_element(By.CSS_SELECTOR,
                                  "#newMark")
    newmark.send_keys("44")

    # 27. Click 'Add More Grades'
    add_more_grades = driver.find_element(By.CSS_SELECTOR,
                                          "#addNewGradeButton")
    add_more_grades.click()

    # 28. Click 'Potions'
    potions = driver.find_element(By.XPATH,
                                  "//td[. = 'Potions']")
    potions.click()

    # 29. Click '44'
    _44 = driver.find_element(By.XPATH,
                              "//td[. = '44']")
    _44.click()

    # 30. Scroll window by ('0','125')
    driver.execute_script("window.scrollBy(0,125)")

    # 31. Click 'Add Student'
    add_student = driver.find_element(By.CSS_SELECTOR,
                                      "#addStudentButton")
    add_student.click()

    # 32. Scroll window by ('0','-219')
    driver.execute_script("window.scrollBy(0,-219)")

    # 33. Scroll window by ('0','-136')
    driver.execute_script("window.scrollBy(0,-136)")

    # 34. Click 'Search'
    search = driver.find_element(By.XPATH,
                                 "//a[. = 'Search']")
    search.click()

    # 35. Click 'search1'
    search1 = driver.find_element(By.CSS_SELECTOR,
                                  "#search")
    search1.click()

    # 36. Type 'Hogwarts' in 'search1'
    search1 = driver.find_element(By.CSS_SELECTOR,
                                  "#search")
    search1.send_keys("Hogwarts")

    # 37. Click 'Search2'
    search2 = driver.find_element(By.CSS_SELECTOR,
                                  "#searchButton")
    search2.click()

    # 38. Scroll window by ('0','1627')
    driver.execute_script("window.scrollBy(0,1627)")

    # 39. Click 'George Weasley'
    george_weasley = driver.find_element(By.XPATH,
                                         "//div[. = ' George Weasley']")
    george_weasley.click()
